on:
  workflow_dispatch:

  schedule:
    - cron: "0 14 * * *"

name: Snotel Plots

jobs:
  run-r-script:
    runs-on: macos-latest
    env: 
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}    
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
        with: 
          use-public-rspm: true
      - uses: r-lib/actions/setup-r-dependencies@v2
        with:
          cache-version: 2
          packages:
            any::ggplot2
            any::tidyverse
            any::data.table
            any::ggforce
            
      - name: run-script
        run: Rscript scripts/Snotel-Plots.R        
        
      - name: commit files
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git add -A
          git commit -m "Saving the results" || echo "no changes to commit"
          git push origin || echo "no changes to commit"
