on:
  workflow_dispatch:
  
name: CRMMS Summary

jobs:
  run-r-script:
    runs-on: macos-latest
    env: 
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}    
    steps:
    - uses: actions/checkout@v4
    - uses: r-lib/actions/setup-r@v2
      with: 
        use-public-rspm: true
    

    - uses: r-lib/actions/setup-pandoc@v2

    - name: Install packages1
      run: Rscript -e 'install.packages("digest", repos="http://cran.us.r-project.org")'

    - name: Install packages
      run: Rscript -e 'install.packages(c("readxl", "flextable","tidyverse","cowplot","reshape2","ggpattern","knitr","rmarkdown"))' 
    
    - name: run-script
      run: Rscript -e 'rmarkdown::render(input = "CRMMS-ESP-Summary.Rmd")'       
        
    - name: commit files
      run: |
        git config --local user.name "$GITHUB_ACTOR"
        git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
        git add -A
        git commit -m "Saving the results" || echo "no changes to commit"
        git push origin || echo "no changes to commit"
